default_agent: app_main
agents:
  app_main:
    name: app_main
    language: python
    node_version: '20'
    entrypoint: C:/projects/amzn-stock-agent/app/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: C:\projects\amzn-stock-agent
    aws:
      execution_role: arn:aws:iam::551670267045:role/amzn-stock-agent-agentcore-role
      execution_role_auto_create: true
      account: '551670267045'
      region: us-east-1
      ecr_repository: 551670267045.dkr.ecr.us-east-1.amazonaws.com/amzn-stock-agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: app_main-X3Fu7U6ukU
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:551670267045:runtime/app_main-X3Fu7U6ukU
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-app_main-builder
      execution_role: arn:aws:iam::551670267045:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-768836f95c
      source_bucket: bedrock-agentcore-codebuild-sources-551670267045-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
